# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(508, 235)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, -1, 511, 241))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 20, 241, 31))
        self.label.setStyleSheet("\n"
"font: 14pt \"Impact\";")
        self.label.setObjectName("label")
        self.button_backup_tela = QtWidgets.QPushButton(self.frame)
        self.button_backup_tela.setGeometry(QtCore.QRect(160, 110, 75, 23))
        self.button_backup_tela.setObjectName("button_backup_tela")
        self.but_restauracao_tela = QtWidgets.QPushButton(self.frame)
        self.but_restauracao_tela.setGeometry(QtCore.QRect(290, 110, 75, 23))
        self.but_restauracao_tela.setObjectName("but_restauracao_tela")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "BACKUP E RESTAURAÇÃO MYSQL"))
        self.button_backup_tela.setText(_translate("Form", "Backup"))
        self.but_restauracao_tela.setText(_translate("Form", "Restauracao"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
